#include "shell.hpp"
#include <iostream>
#include <unistd.h>
#include <cerrno>
#include <limits.h>
#include <dirent.h>
#include "commands/changeDirectory.hpp"
#include "commands/listDirectory.hpp"
#include "commands/printWorkingDirectory.hpp"
#include "commands/printHelp.hpp"